# Generated by Django 4.0 on 2022-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, unique=True, verbose_name='email')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
            ],
            options={
                'verbose_name': 'news_letter_email',
                'verbose_name_plural': 'news_letter_email',
                'db_table': 'news_letter_email',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='name')),
                ('username', models.CharField(max_length=128, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.CharField(max_length=128, unique=True, verbose_name='email')),
                ('contact', models.CharField(blank=True, max_length=128, null=True, verbose_name='phone')),
                ('profile', models.CharField(blank=True, default='default.png', max_length=128, null=True, verbose_name='profile_image')),
                ('authentication', models.BooleanField(default=False, verbose_name='authentication')),
                ('company', models.CharField(blank=True, max_length=128, null=True, verbose_name='company_name')),
                ('tiering', models.BooleanField(default=False, verbose_name='user_tiering')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
            ],
            options={
                'verbose_name': 'users',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
    ]
