# Generated by Django 4.0 on 2022-03-24 09:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='brief',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
