# Generated by Django 4.0 on 2022-03-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_articles_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('project_adversaried', models.IntegerField(choices=[(0, 'private'), (1, 'public'), (2, 'Registered Users of Minefinder')], default=0, verbose_name='project_adversaried')),
                ('commodity', models.CharField(blank=True, max_length=128, null=True, verbose_name='commodity')),
                ('project_loc_x', models.CharField(blank=True, default=0, max_length=128, null=True, verbose_name='project_loc_x')),
                ('project_loc_y', models.CharField(blank=True, default=0, max_length=128, null=True, verbose_name='project_loc_y')),
                ('project_region', models.CharField(blank=True, max_length=128, null=True, verbose_name='project_region')),
                ('project_location', models.TextField(blank=True, null=True, verbose_name='project_location')),
                ('project_field', models.IntegerField(blank=True, choices=[(0, 'Greenfields'), (1, 'Brownfields')], null=True, verbose_name='project_field')),
                ('gis', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='gis')),
                ('map', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='map')),
                ('brief', models.TextField(blank=True, null=True, verbose_name='brief')),
                ('ownership', models.TextField(blank=True, null=True, verbose_name='ownership')),
                ('regional_deposits', models.TextField(blank=True, null=True, verbose_name='regional_deposits')),
                ('exploration', models.TextField(blank=True, null=True, verbose_name='exploration')),
            ],
            options={
                'verbose_name': 'projects',
                'verbose_name_plural': 'projects',
                'db_table': 'projects',
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_category',
            field=models.IntegerField(choices=[(0, 'About Projects'), (1, 'Safety&Security'), (2, 'Evaluation'), (3, 'Rules & Policies')], verbose_name='article_category'),
        ),
    ]
