# Generated by Django 4.0 on 2022-03-25 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_projects_alter_articles_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='upload_date'),
            preserve_default=False,
        ),
    ]
