# Generated by Django 4.0 on 2022-03-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_projects_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('picture', models.ImageField(blank=True, default='', max_length=128, null=True, upload_to='', verbose_name='picture')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallery',
                'db_table': 'gallery',
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='project_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Un-recognised potential'), (1, 'Historical mine'), (2, 'Evidence of Mineralisation'), (3, 'Ore Grades Present'), (4, 'Multiple ore grade intersections'), (5, 'Resouces'), (6, 'Extractable Feasibility')], null=True, verbose_name='project_level'),
        ),
    ]
