# Generated by Django 4.0 on 2022-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gallery_projects_project_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='gis',
            field=models.ImageField(blank=True, null=True, upload_to='gis', verbose_name='gis'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='map', verbose_name='map'),
        ),
    ]
