# Generated by Django 4.0 on 2022-03-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_projects_user_alter_projects_gis_alter_projects_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='bid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='bid'),
        ),
    ]
