# Generated by Django 3.2.12 on 2022-03-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220328_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
