# Generated by Django 3.2.12 on 2022-04-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='p1',
            field=models.ImageField(blank=True, null=True, upload_to='project', verbose_name='picture1'),
        ),
        migrations.AddField(
            model_name='projects',
            name='p2',
            field=models.ImageField(blank=True, null=True, upload_to='project', verbose_name='picture2'),
        ),
    ]
