# Generated by Django 4.0 on 2022-03-24 09:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('brief', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='content')),
                ('public_date', models.DateField(auto_now_add=True, verbose_name='public_date')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='edit_date')),
                ('article_category', models.IntegerField(choices=[(0, 'About Projects'), (1, 'Safety^Security'), (2, 'Evaluation'), (3, 'Rules & Policies')], verbose_name='article_category')),
            ],
            options={
                'verbose_name': 'articles',
                'verbose_name_plural': 'articles',
                'db_table': 'articles',
            },
        ),
    ]
