# Generated by Django 3.2.12 on 2022-03-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_projects_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_loc_x',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_loc_y',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_loc',
            field=models.CharField(blank=True, default=0, max_length=128, null=True, verbose_name='project_loc'),
        ),
    ]
