# Generated by Django 3.2.12 on 2022-04-14 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('home', '0011_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='user'),
        ),
    ]
